version: "3.2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9001:9000"
    networks:
      - backend
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - backend
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  backend:
    external:
      name: {environment}

volumes:
  - sonarqube_conf:/mnt/efs/dev-sonarqube/sonarqube_conf
  - sonarqube_data:/mnt/efs/dev-sonarqube/sonarqube_data
  - sonarqube_extensions:/mnt/efs/dev-sonarqube/sonarqube_extensions
  - sonarqube_bundled-plugins:/mnt/efs/dev-sonarqube/sonarqube_bundled-plugins
  - postgresql:/mnt/efs/dev-sonarqube/postgresql
  - postgresql_data:/mnt/efs/dev-sonarqube/postgresql_data